### ISSUE TITLE
Forms & Records

### ISSUE THREAD

**Issue by MartijnR** [alxndrsn/enketo-collect#1]
The most exciting thing about this project is that you can create a mobile client with a very nice and functional UI. I think it needs a complete redesign (which I'm sure you agree with). This issue is not that but it resolves one of the weirdest UI decisions in ODK Collect, imho.

_A form is a form._
_A record is a record._

Fill Blank form.
Edit Saved **record**.
Send Finalized **record**.
Get Blank Form
Delete Saved Form

**Comment by alxndrsn** [comment]
:+1: was going for a straight copy of the ODK Collect UI to start with, but I agree there is opportunity for clarification :)

**Comment by alxndrsn** [comment]
> This issue is not that but it resolves one of the weirdest UI decisions in ODK Collect, imho.
>
> _A form is a form._
> _A record is a record._

I think I understand the thinking behind the ODK design - if you think about paper forms, you just have blank forms, and filled forms.  And in paper world, a "form definition" is a stack of blank forms provided by head office.  But I don't much see value in using this metaphor in a mobile app.

**Comment by MartijnR** [comment]
Ah yes, that must be what was behind it.
