### ISSUE TITLE
Fetching forms anonymously

### ISSUE THREAD

**Issue by MartijnR** [alxndrsn/enketo-collect#2]
E.g. https://api.ona.io/enketo/formList (when used) will not require a password. So for Ona just filling in the username `enketo` would allow one to retrieve all the forms.

**Comment by alxndrsn** [comment]
How would the username be supplied to the URL?  Does it become a query param, or does it use a basic auth header with a blank password?

**Comment by MartijnR** [comment]
This is not standardized and differs between Aggregate and KoBoToolbox e.g. So for this reason in ODK Collect, users would have to enter:

required:
URL: https://api.ona.io/enketo (and ODK will add /formList and /submission itself).

and then optionally:
Username:
Password

So for a widest-possible use generic Enketo Collect, I think you'd want the same. However, it would of course be very attractive to create custom builds that have a hardcoded URL and can craft the /formList and /submission URLs from just a required username field.

**Comment by alxndrsn** [comment]
Have added a generic OpenRosa adapter.
