### ISSUE TITLE
What is Form Processing Logic?

### ISSUE THREAD

**Issue by alxndrsn** [alxndrsn/enketo-collect#28]
ODK Collect has different options for the Form Processing Logic.  Are these different compatibility modes we would want to support?

**Comment by alxndrsn** [comment]
@MartijnR any ideas on this one?

**Comment by MartijnR** [comment]
I had not heard of it but see it now in the Admin preferences as the last item. It looks like it's a safety feature  after some major engine improvements, allowing users to switch back to an older version. Seems very cumbersome to me.

**Comment by alxndrsn** [comment]
I think we I'll skip this for now then.
