### ISSUE TITLE
ERR_CONNECTION_REFUSED: While trying to transform the XML using the XSLs

### ISSUE THREAD

**Issue by kpulluru** [alxndrsn/enketo-collect#44]
Hi Alex,

When I tried to run the app after browserify, I'm getting the below error.

![image](https://cloud.githubusercontent.com/assets/22320724/18911899/1916712c-859d-11e6-9edb-44a6a925d673.png)

There are 2 things which caught my mind after looking at the error but not sure if they are worth considering.

1) It is triggering a service using port 8081 but there is no service running on that port. Is there any configurations needed for this?
2) The path of the XSL is incorrect as it is deriving the path of index.html and appending "/enketo/*.xsl" while invoking the service.

Not sure if there are any additional configurations are required to be configured but could you please take a look at them and let us know the resolution?

Thanks in advance.

Regards,
Karthik

**Comment by kpulluru** [comment]
Hi Alex,

Any help on the above would be appreciated.

Regards,
Karthik

**Comment by alxndrsn** [comment]
Are you running the app on a phone or an emulator?  Have you tried using the latest APK from https://github.com/alxndrsn/enketo-collect/releases on the same device/emulator, and does it give you the same error?

**Comment by kpulluru** [comment]
I am running the index.html in the chrome browser. Are there any configurations to be done in this case?

**Comment by alxndrsn** [comment]
As long as you're accessing the app over HTTP, then it should work.  I.e. `make www` and then browse to http://localhost:8080

**Comment by alxndrsn** [comment]
I've updated the README to include these instructions - thanks for the nudge :)
