### ISSUE TITLE
Date & Time Field is not working

### ISSUE THREAD

**Issue by kpulluru** [alxndrsn/enketo-collect#45]
Hi Alex,

We are encountering few issues when we execute the app with our own data. When there is a Date&Time field in the form, we are getting the below error.

We have tried to make the jquery version similar to the one used in enketo-core i.e., 2.1.4. We are still getting the error.

Could you please help us on this?

![image](https://cloud.githubusercontent.com/assets/22320724/19644078/6cadd726-9a0b-11e6-9963-499f4834fecd.png)

Regards,
Karthik

**Comment by alxndrsn** [comment]
Hi Karthik,

I can help you with problems with `enketo-collect` here, but not with problems with your app.  If you're having trouble with enketo, you should consult the users mailing list at enketo-users@googlegroups.com.  It will help to give more details of the problem you're seeing, preferably with an accessible code example.

**Comment by kpulluru** [comment]
Hi Alex,

Apologies for the confusion. We are using the enketo-collect app connecting to KoboForms Server. We have created a form with a Date&Time Field in it. There are no modifications done to the source code.
Whenever the app is trying to render the screen after the transformation using XSL, this error is being thrown.

Regards,
Karthik

**Comment by alxndrsn** [comment]
Ah yes, sorry for misreading your initial post.  Can you share the form which is causing the problem?

**Comment by kpulluru** [comment]
Hi Alex,

I have attached the form downloaded from kobo Server. I have attached in XML as well XLS format.

[Date_And_Time_form.zip](https://github.com/alxndrsn/enketo-collect/files/550398/Date_And_Time_form.zip)

**Comment by kpulluru** [comment]
Hi Alex,

Hope you are doing well. I would like to check if you have got a chance to look at this. 

Please let me know if you are looking for any information from my end.

Regards,
Karthik

**Comment by alxndrsn** [comment]
Hi @kpulluru, I haven't looked into this.  Have you made any progress from your end?  Also I have recently upgraded the dependencies for the project, so please re-test with the latest `master` and update this ticket if the behaviour has changed.

**Comment by kpulluru** [comment]
I haven't made any progress on this. I'll try with the latest code to see if it works. I'll keep you posted.

**Comment by alxndrsn** [comment]
Hi @kpulluru, this issue has been inactive for a long time, so I'm closing it.  Please update details and re-open if it's still a problem.
