### ISSUE TITLE
Few field types are not working in iOS devices

### ISSUE THREAD

**Issue by kpulluru** [alxndrsn/enketo-collect#46]
Hi Alex,

There are few field types which are not working in iOS devices whereas the same were working in Android devices.

1) Audio
2) Video
3) Image

These fields when tested in Android, they opened a browse window to select the corresponding file from gallery. But when we test the same in iOS, when clicked on the field it isn't opening anything.

Could you please help us on this?

Regards,
Karthik

**Comment by alxndrsn** [comment]
Hi Karthik,

I have not tested `enketo-collect` on iOS, but please go ahead and file bugs against this project.  It will help a lot if you can include the following in your bug reports:

* git commit hash of the version of `enketo-collect` you are running
* modification you made to build `enketo-collect` for iOS
* screenshots of observed errors (browser console, browser view)
* log output (in text format)

Thanks for your help!

**Comment by alxndrsn** [comment]
Hi @kpulluru, did you manage to solve the issue?  Can you share some more details of how you got things working?

**Comment by kpulluru** [comment]
Hi @alxndrsn, There are no changes done. When we did a clean build, it started working.

**Comment by alxndrsn** [comment]
@kpulluru can you share details of how you're building `enketo-collect` for iOs?

**Comment by kpulluru** [comment]
Hi Alex, I have created a sample ionic project in mac and iOS platform is added by default. I have replaced the www folder with the contents of enketo-collect.

Content copied is as below:
1) bundle.js (Generated after using browserify command)
2) Forms folder
3) Records folder
4) style.css
5) config.html
6) index.html
7) main_menu.html
8) fonts folder
9) enketo folder (with xsl files)

**Comment by alxndrsn** [comment]
@kpulluru that sounds great!  Can you share the source code for your ionic project?

**Comment by kpulluru** [comment]
Hi @alxndrsn, please find the source code attached.

There are few minor changes whcih I have done in this code.
1) Hardcoded (Get blank forms logic) to fetch from kobotoolbox. Username and password should be modified in bundle.js
2) I am not doing the ajax proxy call to transform the xml. I have used earlier version of your code.

[www.zip](https://github.com/alxndrsn/enketo-collect/files/636222/www.zip)
