### ISSUE TITLE
enketo-collect forms not working on windows app

### ISSUE THREAD

**Issue by gowrisankarreddy** [alxndrsn/enketo-collect#48]
Hi Alex,

I a download and started enketo-collect app.its Successfully working fine in chrome.But same code showing error in edge  bundel.js these line    `      return logFn.apply(console, args);` the error message is

> Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","cache":{},"headers":{"Accept":"text/html"},"url":"templates/main_menu.html"},"statusText":""}

please find screenshot chrome

![image](https://cloud.githubusercontent.com/assets/8523227/23998542/7727a962-0a7b-11e7-97af-98f0777ecea5.png)

please find screenshot Edge

![image](https://cloud.githubusercontent.com/assets/8523227/23998597/9581a80e-0a7b-11e7-863c-d5ef95643803.png)

Could you please help us on this?

**Comment by alxndrsn** [comment]
Hi @gowrisankarreddy!  Great to see you're trying out `enketo-collect`.  I don't have access to a machine with Edge on it.  As this code is designed for running on phones, I also have little interest in getting Edge working, but...

I see from the URL in your browser screenshots that you're accessing enketo-collect via the file system, so it's not surprising if things are a little weird.  Ideally you should access it over HTTP.  There's an HTTP server bundled in the repo - you can start it by calling `make www`, and then browse to http://localhost:8080.

Anyway, this HTTP server is still really only to help with developing the software - ideally you should plug an android phone into your computer and run `make` to install the `enketo-collect` app on the phone.

Hope that helps!

**Comment by gowrisankarreddy** [comment]
Hi Alex,

I am installing Appin windows 10 device for your Clarification i am Attached screenshot.Please help me to sort this issue.

**Comment by alxndrsn** [comment]
Hi @gowrisankarreddy, how have you installed on a windows device?  If you've got a windows phone wrapper written for the app, then please share the code - it sounds very cool!

**Comment by alxndrsn** [comment]
Hi @gowrisankarreddy, how have you installed on a windows device?  If you've got a windows phone wrapper written for the app, then please share the code - it sounds very cool!
